### ISSUE TITLE
分类器

### ISSUE THREAD

**Issue by onceforall** [JeeShao/Visual-detection-position#1]

**Comment by JeeShao** [comment]
你好 这个分类器是针对我自己项目的指定物品训练的，而且效果不是很理想，对你可能没有实际意义 也用不到，你需要自己另外训练你需要检测的物品的分类器。

发送自 Windows 10 版邮件应用

发件人: onceforall
发送时间: 2018年10月23日 21:10
收件人: JeeShao/Visual-detection-position
抄送: Subscribed
主题: [JeeShao/Visual-detection-position] 分类器 (#1)

你好，可以分享下circle/cascade.xml和square/cascade.xml两个分类器吗？万分感谢！
